"""The TurnRunner implementation, in the api layer because that is where the
graph is.

`genql/services/` may not import `genql/api/`, and `start_turn` lives here, so
the adapter lives here too and the composition root injects it into the
evaluation service — the same arrangement used for every repository adapter.
The service depends only on the protocol, which `lint-imports` verifies.

A fresh thread id per run, generated by start_turn's own default: an
evaluation has no follow-up turns, and reusing an id would make the second
case resume the first case's checkpoint.
"""

from __future__ import annotations

from typing import Any

from genql.api.query_turn import start_turn
from genql.domain.entities.turn_response import TurnResponse
from genql.domain.ports.thread_lock import ThreadLockFactory


class GraphTurnRunner:
    def __init__(self, graph: Any, locks: ThreadLockFactory) -> None:
        self._graph = graph
        self._locks = locks

    def run(
        self, question: str, datasource_name: str, domain_id: int | None = None
    ) -> TurnResponse:
        return start_turn(self._graph, self._locks, question, datasource_name, domain_id)
