from __future__ import annotations

from typing import Protocol

from genql.domain.entities.thread_summary import ThreadSummary


class ThreadRepository(Protocol):
    def create(self, thread_id: str, user_id: str, datasource_name: str, title: str) -> None: ...
    def touch(self, thread_id: str) -> None: ...
    def list_for_user(self, user_id: str) -> tuple[ThreadSummary, ...]: ...
    def by_id(self, thread_id: str) -> ThreadSummary | None: ...
